version: '3.2'

services:
    php:
        build:
            context: ./php82
            args:
              fcgiport: 8001

        container_name: php82
        ports:
            - '9001:9001'
        links:
             - "redis"
        volumes:
            - ./autolist:/var/www/html
            #- /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

        network_mode: bridge

        depends_on:
            - redis

    redis:
        image: redis
        network_mode: bridge

    # mailhog:
    #     image: mailhog/mailhog:v1.0.0
    #     network_mode: bridge
    #     ports:
    #       - "1025:1025"
    #       - "8025:8025"

